jobs:
- job: iOS_CI_on_Mac
  pool:
    vmImage: 'macOS-10.15'
  timeoutInMinutes: 120
  steps:
    - script: |
        SDK_PATH=`xcrun --sdk iphonesimulator --show-sdk-path`
        python3 $(Build.SourcesDirectory)/tools/ci_build/build.py \
          --build_dir iOS \
          --ios \
          --ios_sysroot $SDK_PATH \
          --osx_arch x86_64 \
          --apple_deploy_target 12.1 \
          --use_xcode \
          --config RelWithDebInfo \
          --parallel \
          --update \
          --test
      displayName: Build onnxruntime for iOS x86_64 and run tests using simulator
